### ISSUE TITLE
Please remove the ssl configuaration details from the conf files 

### ISSUE THREAD

**Issue by nmk32** [collinbarrett/wp-vps-build-guide#10]
You have kept the TLS configuration without installing the SSL certificate and haven't reloaded the server once. I had wasted two hours fixing the ssl issue

**Comment by collinbarrett** [comment]
Hey, sorry about that. It is mentioned in step 24 that it is currently outside the scope of the guide, though. Maybe I should make that more clear when installing the conf file...

Either way, I haven't updated this guide in awhile. Though, I'd like to when I find time. So, it is likely you'll find other issues as well.

Hope it helps!

**Comment by nmk32** [comment]
Please correct the example.conf file or move step no 24 above so that anyone following the guide won't copy the example.conf prior to installing SSL certificate.
