### ISSUE TITLE
Reconsider blocking port 80

### ISSUE THREAD

**Issue by jbradach** [collinbarrett/wp-vps-build-guide#6]
For usability, you may not want to block port 80 here. Just blocking it would prevent users from getting to the site if they typed the domain into the address bar without remembering to include the https://. A more user-friendly solution could be to add a server block listening on 80 that returns a 301 to the https version of the requested page.

Happy to submit as a pull request if you want to go this route.

**Comment by collinbarrett** [comment]
@jbradach thanks. you are right. I typically use CloudFlare for all my sites and set that 80->446 redirection at the CloudFlare level. but, for a general guide, blocking 80 I suppose is a bad idea. feel free to submit a pull, if not I'll update it when I get a chance.

thanks for checking out the guide. I want to finish it, I've just been pulled away the last couple weeks. do you think it is useful?

**Comment by jbradach** [comment]
@collinbarrett Ah ha! I just recently started experimenting with CloudFlare on a couple projects but I just hate having to turn over my DNS to them. I'll aim to submit a pull to address adding a server block to route all HTTP traffic to HTTPS over the next couple days.

I've been looking at numerous ways to create an optimized WordPress configuration (and recently to a lesser degree Drupal). What's been difficult is sifting through all the opinion (crap) that's out there which is why I like that you provide sources throughout. You actually referenced one of my blogs in the ngx_pagespeed sections which is how I came across your project here.

**Comment by collinbarrett** [comment]
@jbradach Oh, you blog on RudeOtter? I can't tell you how many times I've visited that post. haha. Thanks! This guide is essentially a setup I've refined over the last few years. There is a ton of opinion and there seems to be little by the way of "best practice". Time is precious, but if you have any other feedback on this guide, please feel free to share. I'll try to finish up the first draft soon so it can serve as a complete guide for folks.
